# .travis.yml

# references
# https://docs.travis-ci.com/user/tutorials/tutorial-python/

# https://docs.travis-ci.com/user/reference/overview/#linux-examples
# arch: amd64          # optional, this is default, routes to a full VM
# os: linux            # optional, this is default
dist: focal            # or bionic | jammy | xenial with xenial as default

language: python

python:
  - "3.12"

services:
  - postgresql # https://docs.travis-ci.com/user/database-setup/#postgresql



# # https://docs.travis-ci.com/user/database-setup/#use-a-different-postgresql-version
# addons:
#   postgresql: "9.16"

# https://docs.travis-ci.com/user/languages/python/#test-against-multiple-versions-of-dependencies
# env:
#   - DJANGO_VERSION=5.1.7
# install:
#   - pip install -q Django==$DJANGO_VERSION
#   - python setup.py -q install


# to resolve environment variables not found
env:
  global:
  - DATABASE_NAME=travis_ci_test
  - DATABASE_USER=postgres
  - DATABASE_PASSWORD=


# to resolve SECRET_KEY not found using python decouple (https://medium.com/@gilsondev/python-decouple-e-travis-ci-d9cbcd08c20f)
before_script:

install:
  - echo "SECRET_KEY=$SECRET_KEY" >> .env
  - echo "DATABASE_NAME=$DATABASE_NAME" >> .env
  - echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
  - echo "DATABASE_USER=postgres" >> .env
  - psql -c 'create database travis_ci_test;' -U postgres # https://docs.travis-ci.com/user/database-setup/#postgresql
  - pip install -r requirements.txt

script:
  - pytest