"""Generated by Django 5.1.4 on 2025-01-08 21:15"""

from django.db import migrations

import accounts.models

class Migration(migrations.Migration):
    """Migration to alter the CustomUser model's managers to use the CustomUserManager."""

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
