name: Django CI

on:
  push:
    branches: [ "main", "docs" ]
  pull_request:
    branches: [ "main", "docs" ]

jobs:
  build:

    runs-on: ${{ matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
        os: [ubuntu_latest] # ,macOS-latest, windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pdm sync -d -G testing
    - name: Run QA
      run: |
        echo 'django-insecure-*-f)8&%jk%mc2%!4qqi0m+=%-*i8$#ule@!_!n#s1k@xnl3fz5' >> env:SECRET_KEY
        pdm run pytest --junitxml=reports/junit/junit.xml --html=reports/junit/index.html
        coverage run -m pytest tests
        coverage xml
        coverage html
        genbadge coverage
        genbadge tests
